# Enable Gradle caching
org.gradle.caching=true

# Run independent modules in parallel
org.gradle.parallel=true

# Use daemon for faster incremental builds
org.gradle.daemon=true

# Configure on demand
org.gradle.configureondemand=true

# JVM tuning
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Kotlin compiler optimization
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
